version: '3.1'

services:
  database:
    image: postgres
    container_name: movies-battle-database
    ports:
      - "5433:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yan123